# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be63c0e1192e1ef071923d4ba17c9951dd5aff17c9ad1782ee076b6b2d4982da00a21ca26cd53aa58bffcfa4a1d483ef2c0cf3e4769c59eb3064442feaec7bb3

test:
  secret_key_base: ae24ddca207ea0bb08c321d2d4b6d2c810beedccf64e33581dcfcfd97e8257b2c215abc30e6b5fa32f53ddf589d94b3211142c64f27418561bb89000ddc13afe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
